# Generated by Django 5.2 on 2025-05-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormationInscrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('dateN', models.DateField()),
                ('formation', models.CharField(max_length=50)),
                ('frais_formation', models.CharField(max_length=20)),
                ('date_Debut', models.TextField()),
                ('date_Inscription', models.DateTimeField(auto_now_add=True)),
                ('choix_nompayer', models.BooleanField(default=False)),
                ('choix_payer', models.BooleanField(default=False)),
            ],
        ),
    ]
