# Generated by Django 5.2 on 2025-05-31 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formationinscrit',
            old_name='choix_nompayer',
            new_name='choix_nom_payer',
        ),
    ]
