# Generated by Django 5.2 on 2025-05-31 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormation', '0002_rename_choix_nompayer_formationinscrit_choix_nom_payer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formationinscrit',
            old_name='choix_nom_payer',
            new_name='choix_non_payer',
        ),
    ]
