# Generated by Django 5.2 on 2025-06-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormation', '0003_rename_choix_nom_payer_formationinscrit_choix_non_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationinscrit',
            name='frais_formation',
            field=models.FloatField(max_length=100),
        ),
    ]
