# Generated by Django 5.2 on 2025-06-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormation', '0004_alter_formationinscrit_frais_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationinscrit',
            name='frais_formation',
            field=models.IntegerField(),
        ),
    ]
