# Generated by Django 5.2 on 2025-05-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/images/')),
                ('frais_formation', models.IntegerField(blank=True, null=True)),
                ('duree', models.IntegerField()),
                ('date_pub', models.DateField(auto_now_add=True)),
                ('debut_formation', models.DateField(blank=True, null=True)),
                ('nom_prof', models.CharField(blank=True, max_length=200, null=True)),
                ('detail_programme', models.TextField()),
            ],
        ),
    ]
