# Generated by Django 5.2 on 2025-05-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=13)),
                ('photo', models.ImageField(upload_to='static/images/')),
                ('email', models.EmailField(max_length=254)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
